// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PR.OpenGym.Web.Data;

#nullable disable

namespace PR.OpenGym.Web.Migrations
{
    [DbContext(typeof(PROpenGymWebContext))]
    [Migration("20231019050020_AssociateSeedData")]
    partial class AssociateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "28fc5ae8-c637-4bfd-8aa4-23c785a28bfb",
                            ConcurrencyStamp = "cabdf966-1251-4778-8af0-3c7bfa0406a8",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "257020d9-bc80-4821-a6ca-ffef7c787dfa",
                            ConcurrencyStamp = "837e6317-0af0-429b-8de6-cdf9f8bbe90d",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "57c7963f-c1fb-48b9-847a-38deadd11453",
                            RoleId = "28fc5ae8-c637-4bfd-8aa4-23c785a28bfb"
                        },
                        new
                        {
                            UserId = "20e6c427-d499-4fb3-b53b-0e44d99767b7",
                            RoleId = "257020d9-bc80-4821-a6ca-ffef7c787dfa"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PR.OpenGym.Data.Associate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("AssociateMembershipId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Facebook")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImgPath")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssociateMembershipId")
                        .IsUnique();

                    b.HasIndex("BranchId");

                    b.ToTable("Associates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssociateMembershipId = 1,
                            CreatedOn = new DateTime(2023, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(9185),
                            Email = "admin@316fitness.com",
                            FirstName = "Admin",
                            ModifiedOn = new DateTime(2023, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(9185),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AssociateMembershipId = 2,
                            CreatedOn = new DateTime(2023, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(9185),
                            Email = "no-mail@316fitness.com",
                            FirstName = "Visita",
                            ModifiedOn = new DateTime(2023, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(9185),
                            Status = 1
                        });
                });

            modelBuilder.Entity("PR.OpenGym.Data.AssociateDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AssociateId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AssociateId");

                    b.ToTable("AssociateDetails");
                });

            modelBuilder.Entity("PR.OpenGym.Data.AssociateMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("From")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<int>("MembershipStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("To")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.ToTable("AssociateMemberships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(9298),
                            From = new DateTime(2023, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(9298),
                            MembershipId = 1,
                            MembershipStatus = 0,
                            ModifiedOn = new DateTime(2023, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(9298),
                            To = new DateTime(2122, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(9298)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(9298),
                            From = new DateTime(2023, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(9298),
                            MembershipId = 1,
                            MembershipStatus = 0,
                            ModifiedOn = new DateTime(2023, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(9298),
                            To = new DateTime(2122, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(9298)
                        });
                });

            modelBuilder.Entity("PR.OpenGym.Data.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Blvd. la Luz, Las Cruces, 37290 León, Gto.",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "3:16 Fitness - Río Mayo Delta"
                        });
                });

            modelBuilder.Entity("PR.OpenGym.Data.CheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AssociateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssociateId");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("PR.OpenGym.Data.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("AssociateId")
                        .HasColumnType("int");

                    b.Property<string>("Concept")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssociateId");

                    b.HasIndex("ProductId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PR.OpenGym.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PR.OpenGym.Web.Areas.Identity.Data.PROpenGymWebUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "57c7963f-c1fb-48b9-847a-38deadd11453",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "74573664-12a1-490b-ab9d-70f9823d61a3",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN@316FITNESS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAiani0i3CtThr1lPh2pWWd6EJAlAtid2MQtGYoLg5i0OlfVNxP5HpxEZJOBZ8Ftqg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "388f0561-eaed-4189-90dd-caa303d6102e",
                            TwoFactorEnabled = false,
                            UserName = "admin@316fitness.com"
                        },
                        new
                        {
                            Id = "20e6c427-d499-4fb3-b53b-0e44d99767b7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "092eb93c-78db-44d7-a6d7-8923a7375b00",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "USER@316FITNESS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAiani0i3CtThr1lPh2pWWd6EJAlAtid2MQtGYoLg5i0OlfVNxP5HpxEZJOBZ8Ftqg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cca4e424-d805-4a7f-904c-b448dc5399ad",
                            TwoFactorEnabled = false,
                            UserName = "user@316fitness.com"
                        });
                });

            modelBuilder.Entity("PR.OpenGym.Data.Membership", b =>
                {
                    b.HasBaseType("PR.OpenGym.Data.Product");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Membership");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(8802),
                            Description = "30 días",
                            ModifiedOn = new DateTime(2023, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(8898),
                            Name = "Mensual",
                            Price = 499.99m,
                            Period = 30
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(8910),
                            Description = "15 días",
                            ModifiedOn = new DateTime(2023, 10, 18, 23, 0, 19, 951, DateTimeKind.Unspecified).AddTicks(8914),
                            Name = "Quincenal",
                            Price = 299.99m,
                            Period = 15
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PR.OpenGym.Web.Areas.Identity.Data.PROpenGymWebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PR.OpenGym.Web.Areas.Identity.Data.PROpenGymWebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PR.OpenGym.Web.Areas.Identity.Data.PROpenGymWebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PR.OpenGym.Web.Areas.Identity.Data.PROpenGymWebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PR.OpenGym.Data.Associate", b =>
                {
                    b.HasOne("PR.OpenGym.Data.AssociateMembership", "AssociateMembership")
                        .WithOne("Associate")
                        .HasForeignKey("PR.OpenGym.Data.Associate", "AssociateMembershipId");

                    b.HasOne("PR.OpenGym.Data.Branch", "Branch")
                        .WithMany("Associates")
                        .HasForeignKey("BranchId");

                    b.Navigation("AssociateMembership");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("PR.OpenGym.Data.AssociateDetails", b =>
                {
                    b.HasOne("PR.OpenGym.Data.Associate", "Associate")
                        .WithMany()
                        .HasForeignKey("AssociateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Associate");
                });

            modelBuilder.Entity("PR.OpenGym.Data.AssociateMembership", b =>
                {
                    b.HasOne("PR.OpenGym.Data.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("PR.OpenGym.Data.CheckIn", b =>
                {
                    b.HasOne("PR.OpenGym.Data.Associate", "Associate")
                        .WithMany()
                        .HasForeignKey("AssociateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Associate");
                });

            modelBuilder.Entity("PR.OpenGym.Data.Payment", b =>
                {
                    b.HasOne("PR.OpenGym.Data.Associate", "Associate")
                        .WithMany()
                        .HasForeignKey("AssociateId");

                    b.HasOne("PR.OpenGym.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Associate");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PR.OpenGym.Data.AssociateMembership", b =>
                {
                    b.Navigation("Associate");
                });

            modelBuilder.Entity("PR.OpenGym.Data.Branch", b =>
                {
                    b.Navigation("Associates");
                });
#pragma warning restore 612, 618
        }
    }
}
